# Generated by Django 4.2.6 on 2023-10-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_steps',
            field=models.TextField(max_length=10000, verbose_name='Шаги приготовления'),
        ),
    ]
